name: frontend
description: AngelGuide Flutter project
publish_to: 'none' # since this is a local project

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Flutter animation package used in your template
  animations: ^2.0.5

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    # Add any image assets or fonts if needed
    # - assets/images/
